### ISSUE TITLE
The dmg file cheetahcoin_v1.8.0.0_macOS_GUI.dmg can not be opened or run

### ISSUE THREAD

**Issue by idoor88** [ShorelineCrypto/cheetahcoin#21]
I finally found the wallet dmg file from this link: https://github.com/ShorelineCrypto/cheetahcoin/releases/tag/v1.8.0.0, after I downloaded and moved to my Applications folder on my macbook MacOS catalina version 10.15.7, and also I downloaded the MacOS_install folder and followed instructions there to set up everything, then I double clicked on the cheetahcoin_v1.8.0.0_macOS_GUI.dmg file from the Applications folder, the application did not run or open, it seems nothing happened after I double clicked, only the file icon flashed once, then no GUI window showed up.
Also I tried to start up the cheetahcoind since it is a server, then double clicked the dmg file, still the same thing.
Any hints about what is happening?
Thanks in advance!

**Comment by ShorelineCrypto** [comment]
The macOS installation scripts need to be installed. For supported macOS: Catalina or older versions, it should just work.  Post in discord for help if there is any further issues.
