### ISSUE TITLE
Race condition in CCheckQueueControl

### ISSUE THREAD

**Issue by dr-mr-space-monkey** [ShorelineCrypto/cheetahcoin#6]
I've been seeing instances of the wallet crashing when pqueue->nTotal fails to be equivalent to pqueue->nIdle for an assert.

Relevant exception:

> checkqueue.h:167: CCheckQueueControl<T>::CCheckQueueControl(CCheckQueue<T>*) [with T = CScriptCheck]: Assertion `pqueue->nTotal == pqueue->nIdle' failed.

This was something that was also seen on BTC back in Jan/Feb of 2015:
https://github.com/bitcoin/bitcoin/issues/5703

Those folks used a mutex lock prior to evaluating/asserting the pqueue properties:
https://github.com/bitcoin/bitcoin/pull/5721
https://github.com/bitcoin/bitcoin/commit/cf008ac8c3c5d582562d88ad89020daef3e64dcb

**Comment by ShorelineCrypto** [comment]
What wallet were you using when it crashed? QT or CLI, on what OS platform?  When the wallet crashed, was it on CPU mining mode?  or ASIC solo mining mode? Or was it just crashed during regular wallet usage, no mining involved.

**Comment by ShorelineCrypto** [comment]
More info on this crash from discord chats:

```
space__monkey — Today at 7:52 PM
cli ubuntu 20.04
cpu mining mode
honglu69 — Today at 7:54 PM
I see. That would be new info and new crash that I was never aware of.  The error msg you printed, was it on screen or it was on debug.log file:
checkqueue.h:167: CCheckQueueControl<T>::CCheckQueueControl(CCheckQueue<T>*) [with T = CScriptCheck]: Assertion pqueue->nTotal == pqueue->nIdle' failed.`
space__monkey — Today at 7:54 PM
showed up directly on command line
killed the wallet process
honglu69 — Today at 7:55 PM
How frequently you had on this this crash for your Ubuntu 20.04 CPU mining?
space__monkey — Today at 7:56 PM
Honestly it's been sorta random. Noticed it maybe once or twice 2 months ago, but this week it's happened probably a few times every day.
there's nothing that I can see in the debug.log that would indicate an issue when it does happen
honglu69 — Today at 7:57 PM
Did you encounter this same error on Nengcoin side CPU mining?  I would assume you are doing dual mining, right?
space__monkey — Today at 7:58 PM
granted the process doesn't terminate gracefully. Nope nothin on Neng.
```

**Comment by ShorelineCrypto** [comment]
Just checked.  On this  checkqueue.h  file,  NENG and CHTA source code are 100% identical. 
This issue was fixed on bitcoin core version  0.10.1, The fix commit was there:

https://bitcoin.org/en/release/v0.10.1

**Comment by ShorelineCrypto** [comment]
Great news,  I made a commit change on this:
https://github.com/ShorelineCrypto/cheetahcoin/commit/7787377f79d120b9487bc178817913959ba05430

Just tested out in docker and I was able to compile this code.  That is great. This fix will be included in v1.7.x release. Actually this change is mainly on bitcoin core code base, I am going to tag the new release as v0.8.8.x-randomSpike-v1.7.x  versions.  This change plus another litecoin based difficulty routine change should deserve a new version for 0.8.8 tag on main versions part.

**Comment by ShorelineCrypto** [comment]
This was a fix on bitcoin core, most likely tested heavily by bitcoin/litecoin core developers already.  I think it will be fine for this fix to be included in the next hard fork release.

**Comment by dr-mr-space-monkey** [comment]
Outstanding! Closing the issue.

**Comment by ShorelineCrypto** [comment]
The fix and commit is here:
https://github.com/ShorelineCrypto/cheetahcoin/commit/7787377f79d120b9487bc178817913959ba05430
